# Configuration

import os
basedir = os.path.abspath(os.path.dirname(__file__))


class Config(object):
    # 0.0.0.0 - for access from anywhere, 127.0.0.1 - for internal only;
    APP_HOST = '0.0.0.0'
    APP_PORT = 8421
    APP_TITLE = 'Music Browser'
    # for sessions; generated by "import os; os.urandom(24)"
    APP_SECRET_KEY = str(b'Q\xcdR\x0bZ\xed\xa7\xa3\x1d\xd9\xac\xd1P\x16(IE\x80\xacz\xbc\xe9M\xea')
    USE_RELOADER = True
    USE_PAGINATION = True
    TYPES = ('album', 'artist', 'playlist', 'track')
    API_SPOTIFY_URL = 'https://api.spotify.com/v1/search?q={}&type={}&limit={}&offset={}'
    API_SPOTIFY_URL_LIMIT = 50
    API_SPOTIFY_URL_OFFSET = 0

    @staticmethod
    def init_app(app):
        pass


class DevelopmentConfig(Config):
    DEBUG = True
    USE_RELOADER = True


class TestingConfig(Config):
    TESTING = True
    USE_RELOADER = False


class StagingConfig(Config):
    TESTING = True
    USE_RELOADER = False


class ProductionConfig(Config):
    DEBUG = False
    USE_RELOADER = True


config = {
    'development':  DevelopmentConfig,
    'testing':      TestingConfig,
    'staging':      StagingConfig,
    'production':   ProductionConfig,
    'default':      DevelopmentConfig,
}
config_name = os.environ.get('CONFIG_NAME') or 'default'
config_instance = config[config_name]
